Add all existing files to correct directories
jeor0980/TeamChampion pull request #13
Opened 2017-03-15 16:30 UTC by haydenreich

2017-03-15 16:33 UTC, jeor0980 commented
Looks good to me but I'm afraid to approve because I'm still not super familiar with our style guide. Jess halp

2017-03-16 23:34 UTC, jepetty requested changes
Few short questions, but stylistically and comment wise looks good to me! Also if you wouldn't mind removing the two binary files (sortingHat/.sortingHat.py.swp and sortingHat/__pycache__/sortingHat.cpython-35.pyc)

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +#        ret_str = "Group name:\
Keep or remove?

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +    print(G.number_of_nodes())
I think if we leave the print statements in here, we should add some more formatting/data to them (i.e. print('Number of nodes: ', G....)

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +    group.ident = name
Eventually will this be different than group.name? Otherwise we should consider removing this from our group object

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +            print(group.name + " is unpopular")
Hahahaha I love this print statement so much 👍

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +def swapThemBitches(shortGroup, firstPass):
Let's put a TODO comment above this to remind us to change the names before we deliver ;)

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +def swapThemBitches(shortGroup, firstPass):
Oh I like the name though and think we should add a function doc comment as you've done with the others

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +                        #TODO: make this work better
I appreciate your use of TODO comments!!

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +
Correct me if I'm wrong, but as I'm understanding this we've only got 2 chances to make even sized groups? And if after !firstPass the groups aren't the same size then oh well?

Also, unrelated, but I think we should add to our ice box tasks to break the SortThemBitches function up into sub-functions so it's easier to parse (and possibly reusable!). I don't think this is necessary for the first commit though, and I think you could delegate this to someone else (like another algorithm team member, or me ;) )

2017-03-16 23:34 UTC, jepetty commented on sortingHat/sortingHat.py
> +def sortThemBitches():
see earlier TODO comment

2017-03-16 23:34 UTC, jepetty commented on sortingHat/test_sortingHat.py
> +import os
Are we removing the testing directory? It's fine by me if we do, just want to make sure we're also consistent with the data directory existing or not (and, on that note it seems there's 2 test2014data.csv, one in sortingHat directory and one in test_data directory)

2017-03-17 00:13 UTC, jepetty approved these changes

2017-03-17 00:13 UTC, jepetty commented
I just approved so you could merge whenever you wanted to

2017-03-17 02:39 UTC, merged