Hayden branch
jeor0980/TeamChampion pull request #15
Opened 2017-04-03 04:26 UTC by haydenreich

- Directory structure changes
 - Made hatServer into a package
 - Refactored algorithm to pull data from Mongo database rather than the parsed .csv file
 - Added utility to seed the database from the .csv files

2017-04-06 21:45 UTC, jepetty requested changes
Some of my comments were about full removal of the WTForms stuff. I don't know if it's already in master, but I'm happy to open a pull request myself tackling that if you want to keep the focus on configuration of the hatServer.

2017-04-06 21:45 UTC, jepetty commented on hatServer/controllers.py
> +<<<<<<< HEAD:hatServer/controllers.py
Oh, we've got an unresolved merge conflict!

2017-04-06 21:45 UTC, jepetty commented on hatServer/config.py
> +WTF_CSRF_ENABLED = True
I don't know if these two things are still necessary now that we're not using WTForms... Did you need to add them to change the configuration of hatServer?

2017-04-06 21:45 UTC, jepetty commented on hatServer/controllers.py
> +from hatServer.forms import LoginForm
We'll need to remove this line when we remove the WTForms stuff

2017-04-06 21:45 UTC, jepetty commented on hatServer/controllers.py
> +@app.route('/login', methods=['GET', 'POST'])
I do believe this method is also outdated without the forms stuff.

2017-04-06 21:45 UTC, jepetty commented on hatServer/forms.py
> +from flask_wtf import Form
This file can also be removed.

2017-04-06 21:45 UTC, jepetty commented on hatServer/sortingHat/sortingHat.py
> +def dumbledore():
Can we have a comment describing what this method does?

2017-04-06 21:47 UTC, jepetty commented
Also, did you mean to remove all of the angular routing and controller stuff? I thought we were going to stick with the angular routing and not do WTForms?

2017-04-06 22:04 UTC, haydenreich commented
I accidentally wiped the static directory when I moved it under hatServer. So now routing should work again. Oops

2017-04-08 22:10 UTC, jepetty approved these changes

2017-04-08 22:10 UTC, merged